# Generated by Django 6.0.3 on 2026-04-03 08:13

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0002_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
