# Generated by Django 6.0.3 on 2026-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketingapp', '0003_alter_ticket_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='If true, only IT team members (manage IT tickets) can see this comment.'),
        ),
    ]
