# Generated by Django 6.0.3 on 2026-04-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='app_notific_recipie_7952bb_idx',
            old_name='app_notific_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='app_notific_recipie_463879_idx',
            old_name='app_notific_recipie_read_idx',
        ),
    ]
