# Generated by Django 6.0.3 on 2026-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'cabinet',
                'verbose_name_plural': 'cabinets',
                'db_table': 'cabinet',
            },
        ),
        migrations.CreateModel(
            name='GraphicsCardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('memory', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'graphics_card',
                'verbose_name_plural': 'graphics_cards',
                'db_table': 'graphics_card',
            },
        ),
        migrations.CreateModel(
            name='HDDTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'hdd',
                'verbose_name_plural': 'hdds',
                'db_table': 'hdd',
            },
        ),
        migrations.CreateModel(
            name='HeadphoneTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'headphone',
                'verbose_name_plural': 'headphones',
                'db_table': 'headphone',
            },
        ),
        migrations.CreateModel(
            name='KeyboardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'keyboard',
                'verbose_name_plural': 'keyboards',
                'db_table': 'keyboard',
            },
        ),
        migrations.CreateModel(
            name='LiquidCoolerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
                ('is_liquid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'liquid_cooler',
                'verbose_name_plural': 'liquid_coolers',
                'db_table': 'liquid_cooler',
            },
        ),
        migrations.CreateModel(
            name='MachineCabinetThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_cabinet_through',
            },
        ),
        migrations.CreateModel(
            name='MachineGraphicsCardThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_graphicscard_through',
            },
        ),
        migrations.CreateModel(
            name='MachineHDDThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_hdd_through',
            },
        ),
        migrations.CreateModel(
            name='MachineHeadphoneThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_headphone_through',
            },
        ),
        migrations.CreateModel(
            name='MachineKeyboardThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_keyboard_through',
            },
        ),
        migrations.CreateModel(
            name='MachineLiquidCoolerThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_liquidcooler_through',
            },
        ),
        migrations.CreateModel(
            name='MachineMonitorThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_monitor_through',
            },
        ),
        migrations.CreateModel(
            name='MachineMotherboardThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_motherboard_through',
            },
        ),
        migrations.CreateModel(
            name='MachineMouseThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_mouse_through',
            },
        ),
        migrations.CreateModel(
            name='MachinePentableThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_pentable_through',
            },
        ),
        migrations.CreateModel(
            name='MachinePowerSupplyThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_powersupply_through',
            },
        ),
        migrations.CreateModel(
            name='MachineProcessorThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_processor_through',
            },
        ),
        migrations.CreateModel(
            name='MachineRAMThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_ram_through',
            },
        ),
        migrations.CreateModel(
            name='MachineSpeakerThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_speaker_through',
            },
        ),
        migrations.CreateModel(
            name='MachineSSDThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_ssd_through',
            },
        ),
        migrations.CreateModel(
            name='MachineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'machine',
                'verbose_name_plural': 'machines',
                'db_table': 'machine',
            },
        ),
        migrations.CreateModel(
            name='MachineUPSThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_ups_through',
            },
        ),
        migrations.CreateModel(
            name='MachineWebcamThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'machine_webcam_through',
            },
        ),
        migrations.CreateModel(
            name='MonitorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'monitor',
                'verbose_name_plural': 'monitors',
                'db_table': 'monitor',
            },
        ),
        migrations.CreateModel(
            name='MotherboardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('socket', models.TextField(blank=True, null=True)),
                ('memory_slots', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'motherboard',
                'verbose_name_plural': 'motherboards',
                'db_table': 'motherboard',
            },
        ),
        migrations.CreateModel(
            name='MouseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'mouse',
                'verbose_name_plural': 'mouses',
                'db_table': 'mouse',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'operating_system',
                'verbose_name_plural': 'operating_systems',
                'db_table': 'operating_system',
            },
        ),
        migrations.CreateModel(
            name='Pentable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'pentable',
                'verbose_name_plural': 'pentables',
                'db_table': 'pentable',
            },
        ),
        migrations.CreateModel(
            name='PowerSupplyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'power_supply',
                'verbose_name_plural': 'power_supplys',
                'db_table': 'power_supply',
            },
        ),
        migrations.CreateModel(
            name='ProcessorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('architecture', models.TextField(blank=True, null=True)),
                ('cores', models.IntegerField(default=0)),
                ('threads', models.IntegerField(default=0)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('cache', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'processor',
                'verbose_name_plural': 'processors',
                'db_table': 'processor',
            },
        ),
        migrations.CreateModel(
            name='RAMTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('memory', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ram',
                'verbose_name_plural': 'rams',
                'db_table': 'ram',
            },
        ),
        migrations.CreateModel(
            name='SpeakerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'speaker',
                'verbose_name_plural': 'speakers',
                'db_table': 'speaker',
            },
        ),
        migrations.CreateModel(
            name='SSDTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ssd',
                'verbose_name_plural': 'ssds',
                'db_table': 'ssd',
            },
        ),
        migrations.CreateModel(
            name='UPSTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ups',
                'verbose_name_plural': 'upss',
                'db_table': 'ups',
            },
        ),
        migrations.CreateModel(
            name='WebcamTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('assign', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'webcam',
                'verbose_name_plural': 'webcams',
                'db_table': 'webcam',
            },
        ),
    ]
