# Generated by Django 6.0.3 on 2026-03-23 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardwareapp', '0001_initial'),
        ('memberapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinettable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='cabinettable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='cabinettable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='graphicscardtable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='graphicscardtable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphicscard_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='graphicscardtable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='hddtable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='hddtable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdd_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='hddtable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='headphonetable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='headphonetable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headphone_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='headphonetable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='keyboardtable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='keyboardtable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='keyboardtable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='liquidcoolertable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='liquidcoolertable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidcooler_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='liquidcoolertable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinecabinetthrough',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.cabinettable'),
        ),
        migrations.AddField(
            model_name='machinegraphicscardthrough',
            name='graphics_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.graphicscardtable'),
        ),
        migrations.AddField(
            model_name='machinehddthrough',
            name='hdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.hddtable'),
        ),
        migrations.AddField(
            model_name='machineheadphonethrough',
            name='headphone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.headphonetable'),
        ),
        migrations.AddField(
            model_name='machinekeyboardthrough',
            name='keyboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.keyboardtable'),
        ),
        migrations.AddField(
            model_name='machineliquidcoolerthrough',
            name='liquid_cooler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.liquidcoolertable'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='cabinet',
            field=models.ManyToManyField(related_name='machines', through='hardwareapp.MachineCabinetThrough', to='hardwareapp.cabinettable'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='memberapp.department'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='graphics_card',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachineGraphicsCardThrough', to='hardwareapp.graphicscardtable'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='hdd',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachineHDDThrough', to='hardwareapp.hddtable'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='headphone',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachineHeadphoneThrough', to='hardwareapp.headphonetable'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='keyboard',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachineKeyboardThrough', to='hardwareapp.keyboardtable'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='liquid_cooler',
            field=models.ManyToManyField(related_name='machines', through='hardwareapp.MachineLiquidCoolerThrough', to='hardwareapp.liquidcoolertable'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_machines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinessdthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinespeakerthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machineramthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machineprocessorthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinepowersupplythrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinepentablethrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinemousethrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinemotherboardthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinemonitorthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machineliquidcoolerthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinekeyboardthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machineheadphonethrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinehddthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinegraphicscardthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinecabinetthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machineupsthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='machinewebcamthrough',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.machinetable'),
        ),
        migrations.AddField(
            model_name='monitortable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='monitortable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='monitortable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='monitor',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachineMonitorThrough', to='hardwareapp.monitortable'),
        ),
        migrations.AddField(
            model_name='machinemonitorthrough',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.monitortable'),
        ),
        migrations.AddField(
            model_name='motherboardtable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='motherboardtable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='motherboardtable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='motherboard',
            field=models.ManyToManyField(related_name='machines', through='hardwareapp.MachineMotherboardThrough', to='hardwareapp.motherboardtable'),
        ),
        migrations.AddField(
            model_name='machinemotherboardthrough',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.motherboardtable'),
        ),
        migrations.AddField(
            model_name='mousetable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='mousetable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='mousetable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='mouse',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachineMouseThrough', to='hardwareapp.mousetable'),
        ),
        migrations.AddField(
            model_name='machinemousethrough',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.mousetable'),
        ),
        migrations.AddField(
            model_name='operatingsystemtable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='operatingsystemtable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='operating_system',
            field=models.ManyToManyField(related_name='machines', to='hardwareapp.operatingsystemtable'),
        ),
        migrations.AddField(
            model_name='pentable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='pentable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pentable_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='pentable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='pentable',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachinePentableThrough', to='hardwareapp.pentable'),
        ),
        migrations.AddField(
            model_name='machinepentablethrough',
            name='pentable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.pentable'),
        ),
        migrations.AddField(
            model_name='powersupplytable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='powersupplytable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powersupply_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='powersupplytable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='power_supply',
            field=models.ManyToManyField(related_name='machines', through='hardwareapp.MachinePowerSupplyThrough', to='hardwareapp.powersupplytable'),
        ),
        migrations.AddField(
            model_name='machinepowersupplythrough',
            name='power_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.powersupplytable'),
        ),
        migrations.AddField(
            model_name='processortable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='processortable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='processortable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='processor',
            field=models.ManyToManyField(related_name='machines', through='hardwareapp.MachineProcessorThrough', to='hardwareapp.processortable'),
        ),
        migrations.AddField(
            model_name='machineprocessorthrough',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.processortable'),
        ),
        migrations.AddField(
            model_name='ramtable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='ramtable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='ramtable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='ram',
            field=models.ManyToManyField(related_name='machines', through='hardwareapp.MachineRAMThrough', to='hardwareapp.ramtable'),
        ),
        migrations.AddField(
            model_name='machineramthrough',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.ramtable'),
        ),
        migrations.AddField(
            model_name='speakertable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='speakertable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='speakertable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='speaker',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachineSpeakerThrough', to='hardwareapp.speakertable'),
        ),
        migrations.AddField(
            model_name='machinespeakerthrough',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.speakertable'),
        ),
        migrations.AddField(
            model_name='ssdtable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='ssdtable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssd_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='ssdtable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='ssd',
            field=models.ManyToManyField(related_name='machines', through='hardwareapp.MachineSSDThrough', to='hardwareapp.ssdtable'),
        ),
        migrations.AddField(
            model_name='machinessdthrough',
            name='ssd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.ssdtable'),
        ),
        migrations.AddField(
            model_name='upstable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='upstable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ups_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='upstable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machineupsthrough',
            name='ups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.upstable'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='ups',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachineUPSThrough', to='hardwareapp.upstable'),
        ),
        migrations.AddField(
            model_name='webcamtable',
            name='createdby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='webcamtable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcam_records', to='memberapp.team'),
        ),
        migrations.AddField(
            model_name='webcamtable',
            name='updatedby',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='machinewebcamthrough',
            name='webcam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardwareapp.webcamtable'),
        ),
        migrations.AddField(
            model_name='machinetable',
            name='webcam',
            field=models.ManyToManyField(blank=True, related_name='machines', through='hardwareapp.MachineWebcamThrough', to='hardwareapp.webcamtable'),
        ),
        migrations.AddConstraint(
            model_name='cabinettable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_cabinettable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='cabinettable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_cabinettable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='hddtable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_hddtable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='hddtable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_hddtable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='liquidcoolertable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_liquidcoolertable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='liquidcoolertable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_liquidcoolertable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='monitortable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_monitortable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='monitortable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_monitortable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='motherboardtable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_motherboardtable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='motherboardtable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_motherboardtable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='mousetable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_mousetable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='mousetable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_mousetable_remaining_non_neg'),
        ),
        migrations.AlterUniqueTogether(
            name='machinemousethrough',
            unique_together={('machine', 'mouse')},
        ),
        migrations.AddConstraint(
            model_name='pentable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_pentable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='pentable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_pentable_remaining_non_neg'),
        ),
        migrations.AlterUniqueTogether(
            name='machinepentablethrough',
            unique_together={('machine', 'pentable')},
        ),
        migrations.AddConstraint(
            model_name='powersupplytable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_powersupplytable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='powersupplytable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_powersupplytable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='processortable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_processortable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='processortable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_processortable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='ramtable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_ramtable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='ramtable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_ramtable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='speakertable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_speakertable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='speakertable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_speakertable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='ssdtable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_ssdtable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='ssdtable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_ssdtable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='upstable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_upstable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='upstable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_upstable_remaining_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='webcamtable',
            constraint=models.CheckConstraint(condition=models.Q(('assign__gte', 0)), name='hardwareapp_webcamtable_assign_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='webcamtable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining__gte', 0)), name='hardwareapp_webcamtable_remaining_non_neg'),
        ),
    ]
