# Generated by Django 6.0.3 on 2026-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareIssueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_route', models.CharField(max_length=80)),
                ('component_type', models.CharField(max_length=80)),
                ('component_id', models.PositiveIntegerField()),
                ('component_name', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField()),
            ],
            options={
                'verbose_name': 'hardware issue',
                'verbose_name_plural': 'hardware issues',
                'db_table': 'hardware_issue',
            },
        ),
    ]
