# Generated by Django 6.0.3 on 2026-03-23 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _existing_columns(schema_editor, table_name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute(
                """
                SELECT column_name FROM information_schema.columns
                WHERE table_schema = current_schema() AND table_name = %s
                """,
                [table_name],
            )
            return {row[0] for row in cursor.fetchall()}
        if connection.vendor == 'sqlite':
            qn = connection.ops.quote_name(table_name)
            cursor.execute(f"PRAGMA table_info({qn})")
            return {row[1] for row in cursor.fetchall()}
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name FROM information_schema.columns
            WHERE table_name = %s
            """,
            [table_name],
        )
        return {row[0] for row in cursor.fetchall()}


def _existing_index_names(schema_editor, table_name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute(
                """
                SELECT indexname FROM pg_indexes
                WHERE schemaname = current_schema() AND tablename = %s
                """,
                [table_name],
            )
            return {row[0] for row in cursor.fetchall()}
        if connection.vendor == 'sqlite':
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type = 'index' AND tbl_name = ?",
                [table_name],
            )
            return {row[0] for row in cursor.fetchall()}
    return set()


def apply_hardware_issue_0002_if_missing(apps, schema_editor):
    """Apply 0002 schema only for columns/indexes that are not already present."""
    HardwareIssueTable = apps.get_model('hardwareissueapp', 'HardwareIssueTable')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    Team = apps.get_model('memberapp', 'Team')

    table = HardwareIssueTable._meta.db_table
    cols = _existing_columns(schema_editor, table)

    field_specs = [
        (
            'createdby',
            models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(app_label)s_%(class)s_created',
                to=User,
                verbose_name='Created by',
            ),
        ),
        (
            'issued_by',
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hardware_issues_created',
                to=User,
            ),
        ),
        (
            'team',
            models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hardware_issues',
                to=Team,
            ),
        ),
        (
            'updatedby',
            models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(app_label)s_%(class)s_updated',
                to=User,
                verbose_name='Updated by',
            ),
        ),
    ]

    for name, field in field_specs:
        field.set_attributes_from_name(name)
        if field.column not in cols:
            schema_editor.add_field(HardwareIssueTable, field)
            cols.add(field.column)

    idx_names = _existing_index_names(schema_editor, table)
    indexes = [
        models.Index(
            fields=['component_type', 'component_id'],
            name='hardware_is_compone_920c1c_idx',
        ),
        models.Index(
            fields=['-created_at'],
            name='hardware_is_created_7dab01_idx',
        ),
    ]
    for idx in indexes:
        if idx.name not in idx_names:
            schema_editor.add_index(HardwareIssueTable, idx)


class Migration(migrations.Migration):

    dependencies = [
        ('hardwareissueapp', '0001_initial'),
        ('memberapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='hardwareissuetable',
                    name='createdby',
                    field=models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_created',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created by',
                    ),
                ),
                migrations.AddField(
                    model_name='hardwareissuetable',
                    name='issued_by',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='hardware_issues_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name='hardwareissuetable',
                    name='team',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='hardware_issues',
                        to='memberapp.team',
                    ),
                ),
                migrations.AddField(
                    model_name='hardwareissuetable',
                    name='updatedby',
                    field=models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_updated',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated by',
                    ),
                ),
                migrations.AddIndex(
                    model_name='hardwareissuetable',
                    index=models.Index(
                        fields=['component_type', 'component_id'],
                        name='hardware_is_compone_920c1c_idx',
                    ),
                ),
                migrations.AddIndex(
                    model_name='hardwareissuetable',
                    index=models.Index(
                        fields=['-created_at'],
                        name='hardware_is_created_7dab01_idx',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    apply_hardware_issue_0002_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
